delete KHPM.YM_BOARD;
delete KHPM.YM_PRODUCT;
delete KHPM.YM_PRODUCT_CATEGORY;
delete KHPM.YM_RESERVATION_PRODUCT;
delete KHPM.YM_RESERVATION;
delete KHPM.YM_RESERVATION_CAPACITY;
delete KHPM.YM_REVIEW;
delete KHPM.YM_STORE;
delete KHPM.YM_STORE_IMG;
delete KHPM.YM_USER;




Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'admin','admin','사장님','egoksg@naver.com','010-5069-3104',to_date('16/08/16','RR/MM/DD'),'M','Y');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_m20','123','20대 남성 사용자','male20@naver.com','010-5069-3104',to_date('90/11/04','RR/MM/DD'),'M','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_m30','123','30대 남성 사용자','male30@naver.com','010-5069-3104',to_date('80/11/04','RR/MM/DD'),'M','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_m40','123','40대 남성 사용자','male40@naver.com','010-5069-3104',to_date('70/11/04','RR/MM/DD'),'M','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_m50','123','50대 남성 사용자','male50@naver.com','010-5069-3104',to_date('60/11/04','RR/MM/DD'),'M','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_m60','123','60대 남성 사용자','male60@naver.com','010-5069-3104',to_date('50/11/04','RR/MM/DD'),'M','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_f20','123','20대 여성 사용자','female20@naver.com','010-5069-3104',to_date('90/11/04','RR/MM/DD'),'F','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_f30','123','30대 여성 사용자','female30@naver.com','010-5069-3104',to_date('80/11/04','RR/MM/DD'),'F','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_f40','123','40대 여성 사용자','female40@naver.com','010-5069-3104',to_date('70/11/04','RR/MM/DD'),'F','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_f50','123','50대 여성 사용자','female50@naver.com','010-5069-3104',to_date('60/11/04','RR/MM/DD'),'F','N');
Insert into KHPM.YM_USER (USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_HP,USER_BIRTH_DAY,USER_GENDER,IS_ADMIN) values (YM_USER_NO_SEQ.NEXTVAL,'user_f60','123','60대 여성 사용자','female60@naver.com','010-5069-3104',to_date('50/11/04','RR/MM/DD'),'F','N');





Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),1,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),2,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),3,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),4,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),5,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),6,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),7,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),8,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),9,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),10,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),11,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),12,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),13,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),14,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),15,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),16,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),17,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),18,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),19,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),20,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),21,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),22,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),23,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),24,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),25,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),26,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),27,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),28,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),29,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),30,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),31,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),32,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),33,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),34,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),35,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),36,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),37,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),38,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),39,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),40,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),41,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),42,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),43,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),44,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),45,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),46,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),47,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),48,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),49,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),50,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),51,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'게시글 테스트','게시글 테스트입니다.',0,to_date('16/08/16','RR/MM/DD'),52,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'여기 맛 어떤가요?','맛있나요?',1,to_date('16/08/16','RR/MM/DD'),53,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'ㅎㅎㅎㅎ','여기 파스타 어떤가요?',0,to_date('16/08/16','RR/MM/DD'),54,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'여기 누들 맛있나요?','어떤 종류가 맛있나요?',2,to_date('16/08/16','RR/MM/DD'),55,0,0,2);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'약간 짠듯합니다','날에 따라 다르겠지만 저는 그렇게 느꼈습니다',1,to_date('16/08/16','RR/MM/DD'),55,2,1,8);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'스테이크 갑','스테이크가 맛있더군요 ㅎㅎㅎㅎ',1,to_date('16/08/16','RR/MM/DD'),53,1,1,8);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'저는 짜지 않았습니다','상당히 단백하고 맛있더군요',0,to_date('16/08/16','RR/MM/DD'),55,1,1,3);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'약간의 미스가 있었나봅니다','아닌가요?',0,to_date('16/08/16','RR/MM/DD'),55,3,2,3);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'미디움이 갑','딱딱하지 않았습니다',0,to_date('16/08/16','RR/MM/DD'),53,2,2,3);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'상당히 좋아요','전망도좋고 ㅎㅎㅎㅎ',1,to_date('16/08/16','RR/MM/DD'),56,0,0,3);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'아이들도 좋아합니다','버거를 좋아하더군요 음식의 간이 짜지 않았습니다',0,to_date('16/08/16','RR/MM/DD'),57,0,0,8);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'햄버거는 어떤가요?','아이들이 먹을거라 고민되네요',1,to_date('16/08/16','RR/MM/DD'),56,1,1,8);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'애들은 좋아합니다','뿌듯합니다 ㅎㅎㅎㅎㅎㅎ',0,to_date('16/08/16','RR/MM/DD'),56,2,2,3);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'할인카드 소개합니다','국민카드 10%
농협카드 15%
신한카드 10%',0,to_date('2016-08-17 15:33:30','YYYY-MM-DD HH24:MI:SS'),1002,0,0,1);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'공지사항','예약 취소는 해당 날짜로부터 1일 전 까지 가능합니다.',0,to_date('2016-08-17 15:34:30','YYYY-MM-DD HH24:MI:SS'),1001,0,0,1);
Insert into KHPM.YM_BOARD (BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_READ_CNT,BOARD_REG_TIME,BOARD_RE_REF,BOARD_RE_STEP,BOARD_RE_LEVEL,USER_NO) values (YM_BOARD_NO_SEQ.NEXTVAL,'안녕하세요','저희는 이탈리안 레스토랑 KH 입니다.',0,to_date('2016-08-17 15:38:45','YYYY-MM-DD HH24:MI:SS'),1000,0,0,1);




Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Soup',1);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Salad',2);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Pasta',3);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Noodle',4);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Burger',5);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Steak',6);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Sea Food',7);
Insert into KHPM.YM_PRODUCT_CATEGORY (PRODUCT_CATEGORY_NO,PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_ORDER_BY) values (YM_PRODUCT_CATEGORY_NO_SEQ.NEXTVAL,'Dessert',8);





Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Spinach Soup',8000,'유기농 시금치를 이용한 스프입니다.
비타민 A가 채소 중에서 가장 많고 비타민 C와 칼슘, 철분이 풍부한 알카리성 식품인 시금치! 뽀빠이가 즐겨 먹던 완전식품인 시금치는 한창 자라나는 아이들과 임산부에게 적극 추천합니다.','soup.jpg','1471331187747.jpg',1,1);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Chili Soup',9000,'바닥이 두꺼운 큼직한 냄비에 다진 소고기와 홍고추, 향신료를 넣고 끓인 매콤한 스프입니다. 미국 텍사스 일대에서 19세기 중반부터 만들어 먹기 시작한 음식으로 알려져 있다.','soup2.jpg','1471331417635.jpg',2,1);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Crab Soup',10000,'부드러운 게살에 감칠맛 도는 닭육수가 부드럽게 목으로 넘어가는 따끈한 수프 한 그릇에 몸도 마음도 따뜻해집니다.
진하게 우려낸 닭 육수에 게살을 넣고 걸쭉하게 끓인 중국식 수프 요리이다.','soup3.jpg','1471331792022.jpg',3,1);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Chicken Salad',13000,'세포조직을 생성해서 성장을 돕는 닭가슴살샐러드, 고단백 저칼로리의 부드럽고 연한 닭가슴살을 기름에 튀겨 채소류와 어우러지게 담은 다음, 달콤한 드레싱을 뿌려내면 양질의 단백질 섭취는 물론 비타민의 흡수율도 높아진답니다.','salad.jpg','1471332140892.jpg',4,2);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Fruit Salad',12000,'과일 샐러드(Fruit salad)는 과일이 들어간 샐러드이다.
과일뿐 만 아니라, 콘플레이크, 드레싱, 요구르트 등을 곁들여 먹기도 한다. 오렌지, 딸기, 사과, 키위, 블루베리 등을 배합한 요리입니다.','salad3.jpg','1471332497149.jpg',5,2);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Salmon Salad',15000,'연어는 다른 생선에 비해 비타민 A, D등의 지용성 비타민이 풍부하고 단백질과 지방 등 좋은 영양소가 많습니다. 올리브유를 넣은 드레싱과 곁들이면 체내 흡수력이 높아집니다.','salad5.jpg','1471332682429.jpg',6,2);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Ricotta Salad',14000,'리코타 치즈는 이 유청을 원료로 하여 만든 이탈리아 치즈다. 순백색으로 부드러우면서 새콤한 맛이 난다.
발사믹과 리코타 치즈를 곁들인 샐러드입니다.','salad6.jpg','1471333257626.jpg',7,1);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Salmon Pasta',18000,'훈제 연어는 오메가3 지방산이 풍부하게 함유되어있어
종양의 크기를 줄여주고 종양세포의 성장을 억제하는 효과가 있습니다.
훈제연어를 곁들인 파스타입니다.

','pasta.jpg','1471333989473.jpg',8,3);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Beef Pasta',19000,'육질이 연하고 육즙이 많은 최고급 A++ 한우를 이용하여 볶은 파스타입니다.
치즈를 곁들여 풍미를 더했습니다.','pasta2.jpg','1471334321064.jpg',9,3);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Tomato Pasta',17000,'매일 들어오는 신선한 토마토를 올리브유에 살짝 볶아 만드는 깔끔한 맛의 간단한 파스타 요리. 바질은 ‘키친 허브’라고 할 정도로 각종 요리에 널리 사용된다. ','pasta3.jpg','1471334656286.jpg',10,3);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Tofu Noodle',18000,'두부와 버섯 등 채소를 넣어 달걀과 밀가루로 만든 국수로 만든 누들입니다.','noodle.jpg','1471334914454.jpg',11,4);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Chiang Mai Noodle',190000,' 카오쏘이에 사용하는 국수는 바미이다. 남부와 중부 지역에서 사용하는 바미가 밀가루에 달걀 노른자를 섞은 누들입니다.그릇 안을 잘 섞어 먹으면 바삭함과 쫄깃함, 매콤함을 한번에 느낄 수 있다.



','noodle2.jpg','1471335163314.jpg',12,4);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Egg Burger',17000,'오븐에 구운 계란과 토핑으로 이루어진 수제버거입니다.
빵은 후라이팬에 살짝 구워 바삭합니다.','hamber.jpg','1471335349485.jpg',13,5);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Rib Steak',28000,'소의 등 쪽에 있는 부위로서 두터우며 지방이 많아 부드럽습니다.
중간 중간 립에 바비큐소스를 덧발라 구워야 립이 속까지 다 익고 윤기가 많이 나서 먹음직스럽습니다.','steak.jpg','1471335478138.jpg',14,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Tenderloin Steak',26000,'영양소인 비타민 A, B1, C 그리고 에너지원이 되어주는 양질의 단백질이 모두 들어있는 요리에요. 육질을 부드럽게 해주며 소화를 도와주는 배와 고기 냄새를 제거해주는 생강즙으로 밑간을 하여 채소들과 함께 볶아 별미입니다.','steak2.jpg','1471335689867.jpg',15,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Sirloin Steak',28000,'로인의 끝 부분과 우둔살 사이에 위치한 서로인 중에서 육질이 부드러운 톱서로인이 사용된다. 고기 특유의 행은 강해 고기 자체의 맛을 즐기기에 좋다.','steak3.jpg','1471335945037.jpg',16,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Flatiron Steak',30000,'소의 앞다리 위쪽 부분으로 육질이 연하면서도 특유의 쫄깃한 식감을 지니고 있다.
풍부한 지방 풍미와 부드러운 육질로 부담 없이 스테이크를 즐기기 좋고 웰던으로 익혀도 뻣뻣하지 않다.','steak4.jpg','1471336347802.jpg',17,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Beef Steak',22000,'고기는 연한 부분은 그대로, 단단한 부분은 칼 등으로 자근자근 두드려서 굽기 직전에 소금과 후춧가루를 뿌려 모양을 다듬은 다음 냄비에 샐러드유 ·버터를 녹여서 고기의 겉면부터 강한 불에 는 소고기 스테이크입니다.
','steak6.jpg','1471336599283.jpg',18,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Meat Steak',25000,'육질은 잘 운동을 하는 부분이기 때문에 섬유가 거칠며 또한 지방이 적고 살코기의 부분이 많다.  지방이 적고 단백질 함량이 풍부하여 건강한 음식입니다.','steak5.jpg','1471337591179.jpg',19,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Strip Steak',28000,'가장 부드러운 부위인 short-loin(허리부위)을 사용한다. Steak는 loin의 윗부분에 뼈 없는 부분을 사용한다. 지역에 따라 Delmonico steak, shell steak, sirloin club steak, strip steak 등으로 불린다.','steak7.jpg','1471337724296.jpg',20,6);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Lobster',29000,'값비싼 가재요리를 집에서 알뜰하면서도 근사하게 즐기실 수 있답니다. 고소하고 담백한 마늘 버터를 발라 풍미를 높였습니다.','fish.jpg','1471338031531.jpg',21,7);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Grilled Shrimps',18000,'소금에 재운 새우를 팬에 익히면서 로제 소스를 첨가한 새우 구이입니다.
새우는 칼슘과 타우린이 풍부하게 들어 있어 고혈압 예방과 성장 발육에 효과적이고 키토산은 혈액 내 콜레스테롤을 낮추는 역할을 한다.','fish4.jpg','1471338195774.jpg',22,7);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Salmon',22000,'연어를 구워 햄버거 형식으로 홍합을 끼워 해산물의 풍미와 연어의 부드러운 육즙을 즐길 수 있는 요리입니다. 크림 소스로 맛을 더합니다.','fish6.jpg','1471338225582.jpg',23,7);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Fish Steak',26000,'육질이 부드럽고 맛있는 고등어살과 매콤함을 더하는 소스 그리고 담백함을 더하는 그라탕식 소스로 맛을 더했습니다. 소스를 섞어먹으면 더욱 맛있습니다.','fish1.jpg','1471338462914.jpg',24,7);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Mussels',23000,'홍합과 다양한 생선으로 매콤한 홍합요리입니다. 생선살과 채소를 갈아 만든 요리로 여러가지 맛을 느낄 수 있습니다. ','fish3.jpg','1471338577026.jpg',25,7);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Baguette',8000,'크림과 바게트 그리고 견과류로 이루어진 디저트입니다.
바게트(baguette)는 밀가루, 물, 이스트, 소금만으로 만든 가늘고 길쭉한 몽둥이 모양의 프랑스 빵이다.','dessert.jpg','1471338699537.jpg',26,8);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'BurryCake',10000,'폭신폭신하고 부드러운 스펀지시트에 휘핑한 생크림과 딸기를 올려 장식한 딸기생크림 케이크입니다. 촉촉한 식감의 시트와 고소한 생크림, 상큼한 과일의 맛이 조화롭게 어우러져 남녀노소에게 인기있는 케이크입니다.','dessert2.jpg','1471338789757.jpg',27,8);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Mango Pudding',9000,'달걀·우유 등을 주재료로 하여 천으로 싸서 쪄서 만드는데, 따뜻한 디저트로 쓰기도 하고 냉각시켜서 차게 쓰기도 한다. 음식의 온도는 정할 수 있습니다.','dessert3.jpg','1471338994285.jpg',28,8);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Pizza',21000,'팬 피자는 팬을 이용하여 굽는 방식인데 두꺼워서 식사 대용으로 적합하고, 신 피자는 크러스트가 얇은 게 특징이며, 스크린 피자는 스크린이라는 기구를 사용하여 굽는 이탈리아 정통피자이다. 도우의 크기는 정할 수 있습니다.','dessert4.jpg','1471339070548.jpg',29,8);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Macaron',7000,'마카롱(macaron)은 작고 동그란 모양의 머랭 크러스트(meringue crust) 사이에 잼, 가나슈(ganache), 버터크림 등의 필링(filling)을 채워 만든 프랑스 쿠키이다.','dessert5.jpg','1471339118559.jpg',30,8);
Insert into KHPM.YM_PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESC,PRODUCT_IMG_ORIGIN_PATH,PRODUCT_IMG_SYSTEM_PATH,PRODUCT_ORDER_BY,PRODUCT_CATEGORY_NO) values (YM_PRODUCT_NO_SEQ.NEXTVAL,'Choco Cookie',8500,'초코 칩 쿠키는 밀가루, 버터, 달걀로 된 반죽 위에 초콜릿 다진 것과 생크림, 딸기를 얹어 구운 수제과자입니다. 아이들 입맛에 적당합니다.','dessert6.jpg','1471339185050.jpg',31,8);






Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','09:00',30);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','10:30',45);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','12:00',55);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','18:00',60);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','19:30',35);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'D','21:00',30);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','08:00',40);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','09:30',40);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','11:00',50);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','12:30',65);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','16:00',50);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','17:30',55);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','19:00',40);
Insert into KHPM.YM_RESERVATION_CAPACITY (RESERVATION_CAPACITY_NO,RESERVATION_CAPACITY_DW,RESERVATION_CAPACITY_TIME,RESERVATION_CAPACITY_PEOPLE) values (YM_RESERVATION_CAPACITY_NO_SEQ.NEXTVAL,'W','20:30',35);





Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,'없습니다',to_date('2016-08-21 12:30:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'스테이크는 미디움으로 해주세요 아이가 있으니 테이블 준비해주세요',to_date('2016-08-20 17:30:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'없습니다.',to_date('2016-08-21 09:30:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,'없음',to_date('2016-08-22 10:30:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,'없음',to_date('2016-08-21 11:00:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,'너무 달지않게 해주세요',to_date('2016-08-20 17:30:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'미리 준비해주세요',to_date('2016-08-24 09:00:00','YYYY-MM-DD HH24:MI:SS'),4);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,'없습니다',to_date('2016-08-23 18:00:00','YYYY-MM-DD HH24:MI:SS'),4);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'음식이 너무 뜨겁지 않게 해주세요',to_date('2016-08-22 19:30:00','YYYY-MM-DD HH24:MI:SS'),10);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,' ',to_date('2016-08-22 12:00:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,' ',to_date('2016-08-22 18:00:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-23 12:00:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,6,' ',to_date('2016-08-21 19:00:00','YYYY-MM-DD HH24:MI:SS'),7);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,6,' ',to_date('2016-08-23 21:00:00','YYYY-MM-DD HH24:MI:SS'),4);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-21 16:00:00','YYYY-MM-DD HH24:MI:SS'),4);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-21 12:30:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,' ',to_date('2016-08-21 16:00:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-21 20:30:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,6,' ',to_date('2016-08-21 19:00:00','YYYY-MM-DD HH24:MI:SS'),3);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,6,' ',to_date('2016-08-21 12:30:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'아이가 있습니다',to_date('2016-08-20 16:00:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-23 18:00:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,'짜지않게 해주세요',to_date('2016-08-21 08:00:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-24 19:30:00','YYYY-MM-DD HH24:MI:SS'),8);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,4,' ',to_date('2016-08-24 18:00:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,'없습니다',to_date('2016-08-24 12:00:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,'미리 준비해주세요',to_date('2016-08-21 17:30:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,3,' ',to_date('2016-08-24 10:30:00','YYYY-MM-DD HH24:MI:SS'),2);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,' ',to_date('2016-08-21 17:30:00','YYYY-MM-DD HH24:MI:SS'),6);
Insert into KHPM.YM_RESERVATION (RESERVATION_NO,RESERVATION_PEOPLE,RESERVATION_COMMENT,RESERVATION_TIME,USER_NO) values (YM_RESERVATION_NO_SEQ.NEXTVAL,2,' ',to_date('2016-08-20 16:00:00','YYYY-MM-DD HH24:MI:SS'),8);





Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (13,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (13,8,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (13,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (13,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (13,18,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (14,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (14,17,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (14,20,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (14,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (14,5,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (15,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (15,17,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (15,20,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (15,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (15,5,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (16,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (16,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (17,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (17,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (18,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (18,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (19,16,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (24,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (24,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (25,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (25,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (25,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (25,24,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (25,26,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (26,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (26,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (26,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (26,24,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (26,26,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (29,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (29,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (29,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (30,8,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (30,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (30,28,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,11,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,22,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (2,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (9,6,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (9,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (9,17,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (1,2,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (1,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (1,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (1,28,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,4,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,16,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,23,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (3,28,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (5,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (5,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (5,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (6,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (6,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (6,28,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (8,2,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (8,23,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (8,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (20,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (20,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (20,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (20,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (20,25,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (21,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (21,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (21,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (21,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (21,25,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (22,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (22,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (23,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (23,13,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (27,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (27,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (4,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (4,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (4,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (7,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (7,7,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (7,22,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (10,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (10,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (10,29,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (11,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (11,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (11,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (12,1,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (12,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (12,15,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (28,9,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (28,10,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (28,12,1);
Insert into KHPM.YM_RESERVATION_PRODUCT (RESERVATION_NO,PRODUCT_NO,PRODUCT_CNT) values (28,29,1);





Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'참 맛있네요 ㅎㅎㅎㅎ',sysdate,1,0,0,2);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'의외로 스프가 맛있었습니다~',sysdate,2,0,0,7);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'더 좋은 음식으로 준비하도록 노력하겠습니다~ 감사합니다',sysdate,2,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'여기는 언제가도 맛있네요 ㅋㅋㅋㅋㅋ',sysdate,3,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'스테이크가 아주 맛있었습니다. 잘구워져서 나왔어요',sysdate,4,0,0,2);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'늦게 도착해서 조금 식었지만 맛은 좋았습니다.',sysdate,5,0,0,7);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'다른 레스토랑보다 상당히 맛있었어요',sysdate,6,0,0,7);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'예약을 했지만 조금 기다렸습니다 맛은 누들이 제일 기억이 나네요',sysdate,7,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'다시 한번 가보고 싶은 레스토랑입니다',sysdate,8,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'거리가 조금 멀었지만 한번쯤 가볼만 하네요',sysdate,9,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'아이들이 먹기에도 짜지않고 좋습니다',sysdate,10,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'기념일이였는데 분위기 있고 맛도 좋았습니다',sysdate,11,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'상대적으로 짠 느낌이 있지만 디저트나 스프는 간간했습니다',sysdate,12,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'다시오고 싶은 레스토랑이였습니다',sysdate,13,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'분위기있고 스테이크가 맛있었습니다',sysdate,14,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'스프는 조금 짠감이 있지만 파스타는 면이 부드러웠습니다',sysdate,15,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'아이들이 참 좋아했습니다',sysdate,16,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'기념일에 여자친구가 참 좋아하더군요 개인적으로 스프가 맛있었습니다',sysdate,17,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'아이들은 버거를 좋아했고 저희 부부는 스테이크와 샐러드가 참 맛있었습니다',sysdate,18,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'참 맛있었습니다 다음에도 찾아보고 싶은 맛이네요',sysdate,19,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'누들이 상당히 맛있었습니다',sysdate,20,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'음식 간에 조화가 좋았습니다. 특히 파스타가 맛있더군요',sysdate,21,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'스테이크를 웰던으로해도 딱딱하지 않았습니다',sysdate,22,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'누들 국물이 조금짰습니다.',sysdate,23,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'스프와 샐러드가 잘 어울렸습니다',sysdate,24,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'기념일에 가보기 좋은 레스토랑이네요 가격대는 많이 높지 않습니다',sysdate,25,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'브레이크 타임 다음에 바로 갔는데 채소도 신선하고 좋았습니다',sysdate,26,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'코스처럼 요리를 먹었는데 기승전결이 있습니다 파스타와 누들이 맛있었습니다',sysdate,27,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'아이들과 오기에도 좋습니다 분위기있고요',sysdate,28,0,0,8);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'새우구이가 맛있었습니다 버거는 조금 딱딱했습니다',sysdate,29,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'치즈가 아주 부드러웠습니다 스테이크는 미디움이 가장 맛있는듯 하네요',sysdate,30,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'좋은 재료를 쓰는것 같습니다. 요리에대한 설명도 빼놓지 않았습니다',sysdate,31,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'친절하였고 전망도 좋았습니다.',sysdate,32,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'시금치 스프는 단백하니 맛있었습니다 칠리스프는 조금 짰습니다 스테이크는 굽기가 딱 좋았습니다',sysdate,33,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'기념일에 한번 갔습니다 20대 기준으로 가격이 좀 있지만 맛은 있었습니다',sysdate,34,0,0,2);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'디저트는 살짝 달았습니다 스테이크는 맛있었고 음식에 대한 설명도 자세하게 해주셨습니다',sysdate,35,0,0,2);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'집에가는 길에 스테이크가 생각나더군요 맛있었습니다',sysdate,36,0,0,7);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'스프와 빵을 같이 먹으니 맛있었습니다 스테이크는 미디움과 웰던을 먹었는데 둘다 맛있었습니다',sysdate,37,0,0,3);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'감사합니다 다음번에도 음식에 정성을 담겠습니다',sysdate,29,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'소중한 의견 감사합니다',sysdate,37,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'감사합니다 다음번에는 조금 더 자세한 설명 해드리겠습니다',sysdate,31,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'소중한 의견 감사합니다. 참고하여 디저트의 맛을 조절하겠습니다',sysdate,35,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'감사합니다',sysdate,34,1,1,1);
Insert into KHPM.YM_REVIEW (REVIEW_NO,REVIEW_CONTENT,REVIEW_REG_TIME,REVIEW_RE_REF,REVIEW_RE_STEP,REVIEW_RE_LEVEL,USER_NO) values (YM_REVIEW_NO_SEQ.NEXTVAL,'감사합니다',sysdate,32,1,1,1);





Insert into KHPM.YM_STORE (STORE_NAME,STORE_TEL,STORE_ADDR,STORE_DESC,STORE_WEEK_BUSINESS_TIME,STORE_WEEKEND_BUSINESS_TIME) values ('KH 레스토랑','1544-9970','서울 강남구 역삼동 823-24','몸과 마음의 건강을 위해 가공된 식자재의 인위적인 맛보다는 자연 그대로의 환경에서 자란 벌레먹고 못생긴 과일이나 채소를 통하여 투박하지만 건강한, 자연 본연의 가치를 실현하고 있습니다. KH 레스토랑은 동서양의 맛과 멋이 담긴 독특한 메뉴를 선보이는 새로운 감각의 레스토랑으로, 각종 스테이크를 비롯해 양갈비, 랍스터 등 세계적인 요리와 함께 프랑스, 미국, 호주, 칠레 등지에서 들여온 150여가지의 최고급 와인을 즐길 수 있습니다. 또한 격조 높은 공간 속에 비즈니스, 가족모임 등을 위한 두 개의 별실도 마련되어 있습니다.','OPEN : 09:00 / BREAK : 14:00~18:00 / CLOSE : 22:00','OPEN : 08:00 / BREAK : 14:00~16:00 / CLOSE : 22:00');





Insert into KHPM.YM_STORE_IMG (STORE_IMG_SYSTEM_PATH,STORE_IMG_ORIGIN_PATH) values ('1471330435303.jpg','1.jpg');
Insert into KHPM.YM_STORE_IMG (STORE_IMG_SYSTEM_PATH,STORE_IMG_ORIGIN_PATH) values ('1471330435499.jpg','3.jpg');
Insert into KHPM.YM_STORE_IMG (STORE_IMG_SYSTEM_PATH,STORE_IMG_ORIGIN_PATH) values ('1471330435532.jpg','4.jpg');
Insert into KHPM.YM_STORE_IMG (STORE_IMG_SYSTEM_PATH,STORE_IMG_ORIGIN_PATH) values ('1471330435474.jpg','2.jpg');




commit;